/* ──────────────────────────────────────────
   Model: SavedNationalAudit
   Saved national federal oversight audit
   generated by AI. One per month.
   ────────────────────────────────────────── */
import mongoose, { Schema, Document, Model, Types, models } from "mongoose";
import type { INationalAuditReport } from "@/types/national-audit";

export interface ISavedNationalAudit extends Document {
  generatedBy: Types.ObjectId;
  month: string; // e.g., "2025-08"
  auditData: INationalAuditReport;
  createdAt: Date;
  updatedAt: Date;
}

const SavedNationalAuditSchema = new Schema<ISavedNationalAudit>(
  {
    generatedBy: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    month: { type: String, required: true },
    auditData: { type: Schema.Types.Mixed, required: true },
  },
  { timestamps: true },
);

// One national audit per month
SavedNationalAuditSchema.index({ month: 1 }, { unique: true });

export const SavedNationalAudit: Model<ISavedNationalAudit> =
  models.SavedNationalAudit ||
  mongoose.model<ISavedNationalAudit>("SavedNationalAudit", SavedNationalAuditSchema);
